name: Deploy Azure Function Infrastructure

on:
  push:
    branches:
      - main  # lub 'dev', zależnie od strategii
  workflow_dispatch:  # umożliwia ręczne uruchomienie z GUI GitHub

jobs:
  deploy:
    name: Deploy Bicep to Azure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep file
        run: |
          az deployment group create \
            --resource-group ${{ secrets.AZURE_RG }} \
            --template-file mainNS.bicep \
            --parameters location=${{ secrets.AZURE_LOCATION }}
